name: GO Test and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
      
    - name: Test
      run: go test ./calculator -race -v -failfast

    - name: Build
      run: go build -race -o runner
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: sanjibdevnath/gosample
        tags: ${{github.RUNNER_OS}}.${{github.GITHUB_SHA}}.${{ github.GITHUB_ACTION }} ${{github.RUNNER_OS}}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
